<?php

$KEY_NAME = 'name';
$KEY_PASSWORD = 'password';
$KEY_EMAIL = 'email';

$COMPETITION_USER_TYPE_NONE      = -1;
$COMPETITION_USER_TYPE_ORGANIZER = 0;
$COMPETITION_USER_TYPE_ENTRANT   = 1;
$COMPETITION_USER_TYPE_JUDGE     = 2;
$COMPETITION_USER_TYPE_STEWARD   = 3; 
$COMPETITION_USER_TYPES = [ 
  $COMPETITION_USER_TYPE_ORGANIZER => 'Organizer',
  $COMPETITION_USER_TYPE_ENTRANT   => 'Entrant',
  $COMPETITION_USER_TYPE_JUDGE     => 'Judge',
  $COMPETITION_USER_TYPE_STEWARD   => 'Steward',
];

$ORGANIZATION_USER_TYPE_NONE      = -1;
$ORGANIZATION_USER_TYPE_ORGANIZER = 0;
$ORGANIZATION_USER_TYPE_MEMBER    = 1;
$ORGANIZATION_USER_TYPES = [ 
  $ORGANIZATION_USER_TYPE_ORGANIZER => 'Organizer',
  $ORGANIZATION_USER_TYPE_MEMBER    => 'Member',
];

?>
